version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: store_api_tdd-mongodb-1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  api:
    build: .
    container_name: store_api_tdd-api-1
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongodb
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongodb_data: